networks:
  kafka_net:
    driver: bridge

  hdfs_asvsp:
    name: hdfs_asvsp
    external: true

services:
  kafka1:
    image: confluentinc/cp-kafka:7.8.0
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"
      KAFKA_LISTENERS: "PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://0.0.0.0:29092,CONTRO\
        LLER://kafka1:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      CLUSTER_ID: "98D2R1B0T4iSnoL06HXiCw"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
    volumes:
      - ./kafka1/data:/var/lib/kafka/data
    networks:
      - hdfs_asvsp

  kafka2:
    image: confluentinc/cp-kafka:7.8.0
    hostname: kafka2
    container_name: kafka2
    ports:
      - "9094:9092"
      - "9095:9093"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_BROKER_ID: 2
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"
      KAFKA_LISTENERS: "PLAINTEXT://kafka2:9092,CONTROLLER://kafka2:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka2:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      CLUSTER_ID: "98D2R1B0T4iSnoL06HXiCw"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
    volumes:
      - ./kafka2/data:/var/lib/kafka/data
    networks:
      - hdfs_asvsp

  kafka3:
    image: confluentinc/cp-kafka:7.8.0
    hostname: kafka3
    container_name: kafka3
    ports:
      - "9096:9092"
      - "9097:9093"
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_BROKER_ID: 3
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"
      KAFKA_LISTENERS: "PLAINTEXT://kafka3:9092,CONTROLLER://kafka3:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka3:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      CLUSTER_ID: "98D2R1B0T4iSnoL06HXiCw"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
    volumes:
      - ./kafka3/data:/var/lib/kafka/data
    networks:
      - hdfs_asvsp

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-cluster-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092,kafka2:9092,kafka3:9092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - schema-registry
    networks:
      - hdfs_asvsp

  schema-registry:
    image: confluentinc/cp-schema-registry:7.8.0
    hostname: schema-registry
    container_name: schema-registry
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka1:9092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks:
      - hdfs_asvsp

  email-service:
    build:
      context: ./email-service/email-service
      dockerfile: Dockerfile
    environment:
      KAFKA_BROKERS: "kafka1:9092,kafka2:9092,kafka3:9092"
      SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      SMTP_USERNAME: "josejosemou8@gmail.com"
      SMTP_PASSWORD: "gwkd jrdh cjoo expz"
    ports:
      - "6060:6060"
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - schema-registry
    networks:
      - hdfs_asvsp

  auth-service:
    container_name: auth-service
    build:
      context: ./auth-service/auth-service
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://admin:1MUAw9FvbtFpgqE9@postgres:5432/auth_db
      PORT: "5050"
    ports:
      - "5050:5050"
    depends_on:
      - go-backend
      - postgres
    networks:
      - hdfs_asvsp

  stream-generator:
    container_name: stream-generator
    build:
      context: ./faker-generators/stream-generator/stream-generator
      dockerfile: Dockerfile
    environment:
      KAFKA_BROKERS: "kafka1:9092,kafka2:9092,kafka3:9092"
      SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      SCHEMAS_PATH: "/app/schemas/streams-schemas"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "ppgQ;g+rg()u9vhi"
      SCRIPT_PATH: "/app/scripts/main.cjs"
    volumes:
      - ./schemas:/app/schemas:ro
      - ./faker-generators/stream-generator/bundled:/app/scripts:ro
    ports:
      - "6666:6666"
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - schema-registry
      - redis
    networks:
      - hdfs_asvsp

  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1MUAw9FvbtFpgqE9
      POSTGRES_DB: auth_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - hdfs_asvsp

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 1MUAw9FvbtFpgqE9
    ports:
      - "5454:80"
    depends_on:
      - postgres

  redis:
    container_name: redis
    image: redis:7.4-alpine
    restart: always
    environment:
      REDIS_PASSWORD: "ppgQ;g+rg()u9vhi"
    ports:
      - "6379:6379"
    entrypoint: sh -c 'redis-server --save 20 1 --loglevel warning --requirepass
      "$$REDIS_PASSWORD"'
    volumes:
      - redis_data:/data
    networks:
      - hdfs_asvsp

  go-backend:
    build:
      context: ./go/src/github.com/milibovan/application
      dockerfile: Dockerfile
    container_name: go-backend
    volumes:
      - ./schemas:/app/schemas
      - ./go/src/github.com/milibovan/network:/network
    ports:
      - "7070:7070"
    environment:
      KAFKA_BROKERS: "kafka1:9092,kafka2:9092,kafka3:9092"
      SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "ppgQ;g+rg()u9vhi"
      SCHEMA_PATH: "/app/schemas/notification-event.avsc"
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - schema-registry
    networks:
      - hdfs_asvsp
    restart: unless-stopped

volumes:
  redis_data:
    driver: local
  postgres_data:
