FROM rust:latest AS builder
WORKDIR /app

COPY . .
RUN cargo build --release

FROM debian:trixie-slim
WORKDIR /app

RUN apt-get update && apt-get install -y curl ca-certificates && \
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/target/release/stream-generator .

EXPOSE 6666

CMD ["./stream-generator"]