// Code generated by avro/gen. DO NOT EDIT.
package models

// This is schema for email notification type in Kafka.
type NotificationEvent struct {
	ID string `avro:"id"`
	// Event type and also email template.
	EventType string `avro:"event_type"`
	// Who should receive this notification.
	RecipientType string `avro:"recipient_type"`
	// ID of the recipient (user_id or trader_id).
	RecipientID string `avro:"recipient_id"`
	Timestamp   int64  `avro:"timestamp"`
	// If set, send notification at this time (Unix timestamp). Null = send immediately.
	ScheduledSendTime *int64 `avro:"scheduled_send_time"`
	// Which channel notification should be sent to.
	Channel  string            `avro:"channel"`
	OrderID  string            `avro:"order_id"`
	UserID   string            `avro:"user_id"`
	TraderID string            `avro:"trader_id"`
	Data     map[string]string `avro:"data"`
}
