services:
  jobmanager:
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        jobmanager.archive.expiration-time: 1 hour
        historyserver.archive.clean-up: false
        jobmanager.archive.fs.dir: file:///opt/flink/completed-jobs
        env.java.opts.all: --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
      - HADOOP_CLASSPATH=/opt/hadoop/etc/hadoop
    networks:
      - hdfs_asvsp
    volumes:
      - ../airflow/files/flink/my_jobs:/opt/flink/usrlib
      - flink_history:/opt/flink/completed-jobs
      
  taskmanager:
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: taskmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        jobmanager.archive.expiration-time: 1 hour
        historyserver.archive.clean-up: false
        jobmanager.archive.fs.dir: file:///opt/flink/completed-jobs
        env.java.opts.all: --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
      - HADOOP_CLASSPATH=/opt/hadoop/etc/hadoop
    depends_on:
      - jobmanager
    deploy:
      replicas: 2
    networks:
      - hdfs_asvsp
    volumes:
      - ../airflow/files/flink/my_jobs:/opt/flink/usrlib
      - flink_history:/opt/flink/completed-jobs

volumes:
  flink_history:

networks:
  hdfs_asvsp:
    name: hdfs_asvsp
    external: true